### PR TITLE
Fix builds by checking out submodules

### LINKED ISSUE #56: Ubuntu & macOS builds failing
It looks like all recent [Ubuntu builds](https://github.com/3rdparty/eventuals-grpc/actions/workflows/ubuntu.yml): and [macOS builds](https://github.com/3rdparty/eventuals-grpc/actions/workflows/macos.yml) have been failing for a few weeks.

Sample error: https://github.com/3rdparty/eventuals-grpc/runs/4608427962?check_suite_focus=true

Run bazel build --spawn_strategy=local --copt="-g" --strip="never" :grpc
  bazel build --spawn_strategy=local --copt="-g" --strip="never" :grpc
  shell: /usr/bin/bash -e {0}
  env:
    LLVM_PATH: /home/runner/work/eventuals-grpc/eventuals-grpc/llvm
    LD_LIBRARY_PATH: /home/runner/work/eventuals-grpc/eventuals-grpc/llvm/lib:
    DYLD_LIBRARY_PATH: /home/runner/work/eventuals-grpc/eventuals-grpc/llvm/lib:
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: Error fetching repository: java.io.IOException: No WORKSPACE file found in /home/runner/.cache/bazel/_bazel_runner/a7f112ba8f19a25df8d20f939434879e/external/com_github_3rdparty_eventuals
ERROR: no such package '@com_github_3rdparty_eventuals//bazel': No WORKSPACE file found in /home/runner/.cache/bazel/_bazel_runner/a7f112ba8f19a25df8d20f939434879e/external/com_github_3rdparty_eventuals
INFO: Elapsed time: 4.158s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
Error: Process completed with exit code 1.

### PR DESCRIPTION
**Pull request by CodingCanuck**
Fixes #56.

### CODE REVIEW

**Comment by CodingCanuck** [comment]
Builds are still running for 3 minutes now: https://github.com/3rdparty/eventuals-grpc/runs/4695374734?check_suite_focus=true https://github.com/3rdparty/eventuals-grpc/runs/4695374736?check_suite_focus=true

But gosh do they look fixed, since they're not failing after 4s with "No WORKSPACE file found" errors like in https://github.com/3rdparty/eventuals-grpc/runs/4608427962?check_suite_focus=true

So I suspect this fixes things.

**Comment by CodingCanuck** [comment]
> Builds are still running for 3 minutes now: https://github.com/3rdparty/eventuals-grpc/runs/4695374734?check_suite_focus=true https://github.com/3rdparty/eventuals-grpc/runs/4695374736?check_suite_focus=true
> 
> But gosh do they look fixed, since they're not failing after 4s with "No WORKSPACE file found" errors like in https://github.com/3rdparty/eventuals-grpc/runs/4608427962?check_suite_focus=true
> 
> So I suspect this fixes things.

Confirmed that this fixes builds, since the ubuntu build & test has finished building: https://github.com/3rdparty/eventuals-grpc/runs/4695374736?check_suite_focus=true (ubuntu tests are still running, and mac build is still running: https://github.com/3rdparty/eventuals-grpc/runs/4695374734?check_suite_focus=true )

**Review by ArthurBandaryk — APPROVED** [review]
LGTM! ty Alex!

**Comment by ArthurBandaryk** [comment]
@while-false could you please remove the old `check_code_format` action to be able to merge this PR?

**Comment by CodingCanuck** [comment]
> Formatting Check

> @while-false could you please remove the old `check_code_format` action to be able to merge this PR?

Arthur, can you say more about this? Do we need to delete https://github.com/3rdparty/eventuals-grpc/blob/main/.github/workflows/check_format_code.yml ? You mention it's an old check: is there something newer that replaces it, like https://github.com/3rdparty/eventuals-grpc/blob/main/tools/pre-commit ? If so, how does that get run?

(Gorm's out this week so I can try to send out more fixes, or we can bundle everything into this PR to make it a "get things working" generic fix)

**Comment by CodingCanuck** [comment]
> > Formatting Check
> 
> > @while-false could you please remove the old `check_code_format` action to be able to merge this PR?
> 
> Arthur, can you say more about this? Do we need to delete https://github.com/3rdparty/eventuals-grpc/blob/main/.github/workflows/check_format_code.yml ? You mention it's an old check: is there something newer that replaces it, like https://github.com/3rdparty/eventuals-grpc/blob/main/tools/pre-commit ? If so, how does that get run?
> 
> (Gorm's out this week so I can try to send out more fixes, or we can bundle everything into this PR to make it a "get things working" generic fix)

I just filed https://github.com/3rdparty/eventuals-grpc/issues/59 to discuss the format check being seemingly broken: let's discuss there.

**Comment by CodingCanuck** [comment]
> > > Formatting Check
> > 
> > 
> > > @while-false could you please remove the old `check_code_format` action to be able to merge this PR?
> > 
> > 
> > Arthur, can you say more about this? Do we need to delete https://github.com/3rdparty/eventuals-grpc/blob/main/.github/workflows/check_format_code.yml ? You mention it's an old check: is there something newer that replaces it, like https://github.com/3rdparty/eventuals-grpc/blob/main/tools/pre-commit ? If so, how does that get run?
> > (Gorm's out this week so I can try to send out more fixes, or we can bundle everything into this PR to make it a "get things working" generic fix)
> 
> I just filed #59 to discuss the format check being seemingly broken: let's discuss there.

I think #59 is fixed now, so this PR should now auto-merge once this second round of builds completes (probably in ~30 minutes).

**Comment by ArthurBandaryk** [comment]
> > > > Formatting Check
> > > 
> > > 
> > > > @while-false could you please remove the old `check_code_format` action to be able to merge this PR?
> > > 
> > > 
> > > Arthur, can you say more about this? Do we need to delete https://github.com/3rdparty/eventuals-grpc/blob/main/.github/workflows/check_format_code.yml ? You mention it's an old check: is there something newer that replaces it, like https://github.com/3rdparty/eventuals-grpc/blob/main/tools/pre-commit ? If so, how does that get run?
> > > (Gorm's out this week so I can try to send out more fixes, or we can bundle everything into this PR to make it a "get things working" generic fix)
> > 
> > 
> > I just filed #59 to discuss the format check being seemingly broken: let's discuss there.
> 
> I think #59 is fixed now, so this PR should now auto-merge once this second round of builds completes (probably in ~30 minutes).

Wow, exactly! check_format_code is an unexisting action which never ends:) Since I have no permissions to update branch protection rules I asked Gorm:)
Anyway ty for dealing with this!

**Pull request merged**
