### PR TITLE
Rename old repo

### PR DESCRIPTION
**Pull request by ArthurBandaryk**
Since we've renamed the grpc's repo for being `eventuals-grpc` we need to update this names in GitHub actions too.

### CODE REVIEW

**Review by CodingCanuck — APPROVED** [review]
Ben's out the next two days, so hopefully he won't mind if I approve this :)

**Comment by CodingCanuck** [comment]
It looks like Ubuntu + Mac builds are failing on this PR, which also happened to me last week: https://github.com/3rdparty/eventuals-grpc/issues/56

I'm still quite unfamiliar with our build system: is this something you know how to debug? Or alternatively, can/should we temporarily bypass these failures when merging this PR while we resolve whatever's broken?

**Comment by ArthurBandaryk** [comment]
> 

Good question Alex! For now I'm not aware of the reason why these actions fail . I think we can bypass these failures when merging this PR as we have done for example with this [PR](https://github.com/3rdparty/eventuals-grpc/pull/54).

**Comment by CodingCanuck** [comment]
> > 
> 
> Good question Alex! For now I'm not aware of the reason why these actions fail . I think we can bypass these failures when merging this PR as we have done for example with this [PR](https://github.com/3rdparty/eventuals-grpc/pull/54).

Makes sense. How does bypassing work? Is that something they PR author does? (I'd love some steps to follow in case I need to do the same)

In the meantime, I think https://github.com/3rdparty/eventuals-grpc/pull/58 might fix the broken builds.

**Comment by ArthurBandaryk** [comment]
> > > 
> > 
> > 
> > Good question Alex! For now I'm not aware of the reason why these actions fail . I think we can bypass these failures when merging this PR as we have done for example with this [PR](https://github.com/3rdparty/eventuals-grpc/pull/54).
> 
> Makes sense. How does bypassing work? Is that something they PR author does? (I'd love some steps to follow in case I need to do the same)
> 
> In the meantime, I think #58 might fix the broken builds.

I do not have the access to bypassing work:) I think you should ask Ben/RJ/Gorm this question:)

**Comment by CodingCanuck** [comment]
> > > > 
> > > 
> > > 
> > > Good question Alex! For now I'm not aware of the reason why these actions fail . I think we can bypass these failures when merging this PR as we have done for example with this [PR](https://github.com/3rdparty/eventuals-grpc/pull/54).
> > 
> > 
> > Makes sense. How does bypassing work? Is that something they PR author does? (I'd love some steps to follow in case I need to do the same)
> > In the meantime, I think #58 might fix the broken builds.
> 
> I do not have the access to bypassing work:) I think you should ask Ben/RJ/Gorm this question:)

Since all three of those folks are out for a few days, here's my best guess: if any admin manually merged a PR, it bypassed all requirements until recently: that was raised and fixed in https://github.com/3rdparty/eventuals/issues/164.

Now, requirements are actually requirements! :D D:

So I think the cleanest thing to do is to get these checks passing before submission: I think https://github.com/3rdparty/eventuals-grpc/pull/58 should fix the existing break and unblock this PR.

**Comment by ArthurBandaryk** [comment]
> 

Fully agreed Alex! Let's wait for merging [#58](https://github.com/3rdparty/eventuals-grpc/pull/58) and only then deal with this PR!

**Comment by CodingCanuck** [comment]
> > 
> 
> Fully agreed Alex! Let's wait for merging [#58](https://github.com/3rdparty/eventuals-grpc/pull/58) and only then deal with this PR!

#58 is merged: merge away!

**Pull request merged**
